### ISSUE TITLE
suggested change

### ISSUE THREAD

**Issue by abuxton** [kreeuwijk/puppet-sqlserver_mgmt#1]
Restore from, backup and features such as should be separate boolean variables, not part for the single hash
Context is lost and clarity lost in the use of the class, 
class sqlserver_mgmt (
  $sql_config = lookup('sql', Hash, 'hash', { 'configs' => {}, 'databases' => {}, 'logins' => {}, 'users' => {} })
){

suggest something like, otherwise it is pretty automagic and not contextual code
class sqlserver_mgmt (
sql_config
sql_backup
sql_restore
sql db_data
sql_server_login
)

**Comment by kreeuwijk** [comment]
ok, separating this out may negate the need for Hash merging across Hiera levels. I also checked the documentation and saw that APL with hash merging is still possible by setting lookup_options.

I would suggest the following breakup of variables:
class sqlserver_mgmt (
  $configs      = {},
  $databases = {},
  $logins         = {},
  $users          = {},
)

This would basically breakup the 4 sublevels of the original complex variable into 4 seperate variables.

**Comment by kreeuwijk** [comment]
Fixed in code
